[workspace]
members = [
  "packages/zero-app-core",
  "packages/zero-app"
]

[workspace.package]
version = "1.0.0"

[workspace.dependencies]
tauri-build = { version = "1.3", features = [] }
tauri = { version = "1.3", features = ["shell-open"] }
